import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

export const metadata: Metadata = {
  title: "Personal Website",
  description: "Generated by create nextjs + sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto py-20">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-green-600  text-2xl font-bold hover:pointer-cursor"
          >
            Subash
          </Link>
          <div className="flex items-center gap-5 font-serif text-sm text-gray-100">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-40">{children}</main>
      </body>
    </html>
  );
}
