import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Personal Website',
  description: 'Generated by create nextjs + sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
        {children}
        </body>
    </html>
  )
}
